### ISSUE TITLE
Login to Cisco router with banners

### ISSUE THREAD

**Issue by unchained-za** [cmp-202/ssh2shell#41] opened 2017-09-22 13:13 UTC
I typically have to login to routers with login and motd banners. These often end with # or > characters, which then gets confused with the login prompt, causing command and responses to be out of sync in future operations. I picked that up when trying to process the enable command's Password: prompt. I also cannot disable these prompt characters as I need to look for both of them. Basically looking for a way to ensure that I've empties the input stream by the time I start sending commands.
In the specific case that I'm testing on I have a single line motd banner that ends with >. This banner then gets returned as the response for the first command iso the actual response, so everything seems to be out of phase by one line.

**Comment by cmp-202** [comment] 2017-09-23 15:53
Try using `host.verbose = true` you will see the command->response blocks as the code detects each standard prompt. Do you see the same out of sync detail in the verbose response or is it in the full session response text? Does the first command get missed or are there any that are missed. The `sshObj.sessionText` has the buffer appended onto it before onCommandCommplete is emitted so that content should be sequential for each "prompt" detection and buffer content. 

The process is event driven on every data event received by the stream meaning every character triggers the prompt test so both '>' received will triger a standard prompt detected command complete event. This will load the next command in the array and write it to the stream but only the second time is the detection actually a prompt and the stream in a state to write to the waiting prompt. That is why I asked if the first command was missed. You could see the first command but no response and then the second command and second response etc, not sure if that is the case for you.
 
If the first command is missed then you could try adding a command at the start of the command array that won't be run, knowing it will be dropped, or you can add handling in `host.onCommandComplete` handler to detect the initial > and manipulate the next command to run and state of commands array to mimic ingnoring it.

**Comment by unchained-za** [comment] 2017-09-23 17:19
Please see below. Cisco.txt is the actual node.js, quite butchered at this stage. The fine.txt is the output with a normal cisco router (GNS emulation) without the motd banner and prob.txt is the output with the router (also on GNS) that has the interfering motd banner. This was also a serious problem for me in my C++ implementation but got past it eventually. With the moving to Node.js we'd like to use a full node implementation and ssh2shell seems like a perfect interface. I have to check for normal and enabled prompts and do the enable command if required (test still to be added). The first problem is however to detect the real prompt correctly, which seems to happen if I go directly to ssh2.
[fine.txt](https://github.com/cmp-202/ssh2shell/files/1326683/fine.txt)
[prob.txt](https://github.com/cmp-202/ssh2shell/files/1326684/prob.txt)
[cisco.txt](https://github.com/cmp-202/ssh2shell/files/1326685/cisco.txt)

**Comment by cmp-202** [comment] 2017-09-23 23:34
Thanks for those files it really makes a difference being able to see the runtime process and content.
You will notice there is no onCommandProcessing debug showing in you prob.txt for the first command caused by the prompt detection before the buffer is fully loaded to the actual prompt. If we can clear the buffer when a standard prompt char is the next character on that first lot of data we should be able to subvert the first prompt detection.

Solution:
Check for the first standard prompt char in `host.onCommandProcessing` handler and shift the buffer (response) content into the sshObj.sessionText and clear the buffer. That retains the content in the session text but returns the buffer to a state where the rest of the data can be received without triggering a false positive.

Something like:
```javascript
onCommandProcessing: function( command, response, sshObj, stream ) {
        //Check the command and prompt exits and respond with a 'y' but only does it once
        if (sshObj.debug) {this.emit('msg', this.sshObj.server.host + ": Check for false prompt or enable");}
        if (sshObj.verbose) {this.emit('msg', this.sshObj.server.host + ": command: " + command + ", response: ||" + response + "||, firstRun: " + sshObj.firstRun);}
        if (command === "" and response.match("[" + sshObj.standardPrompt + "]$").length > 0 and sshObj.falsePromptDetected === false){
            sshObj.falsePromptDetected = true;
            sshObj.sessionText += response;
            response = "";
        } else if (command === "enable" && response.indexOf("assword:") > 0 && sshObj.firstRun != true) {
            //This debug message will only run when conditions are met not on every data event so is ok here
            if (sshObj.debug) {this.emit('msg', this.sshObj.server.host + ": Responding to enable with " + sshObj.server.password);}
            sshObj.firstRun = true
            stream.write(sshObj.server.password + '\r\n');
        }
    }
``` 
I have modified your script to remove defaults you don't need to set and adjusted debug to verbose where it is content related not sequence information and I have added the onCommandProccessing test.
It might need a tweek but see how it goes.

[cisco.txt](https://github.com/cmp-202/ssh2shell/files/1326942/cisco.txt)

**Comment by unchained-za** [comment] 2017-09-24 12:09
It seems like onCommandProcessing is not reached for the first command on the problematic Cisco router.

10.15.0.50: Connection.connect
Connected
10.15.0.50: Connection.ready
Ready
10.15.0.50: Connection.shell
10.15.0.50: Normal prompt detected
10.15.0.50: Host.commands: `Send commands`,show clock,enable,term len 0,show run
10.15.0.50: Next command from host.commands: `Send commands`
10.15.0.50: Notifications: sessionText output
Send commands
10.15.0.50: Host.commands: show clock,enable,term len 0,show run
10.15.0.50: Next command from host.commands: show clock
10.15.0.50: Notifications: Normal Command to run
10.15.0.50: running: show clock
10.15.0.50: Normal prompt detected
10.15.0.50: Command complete:
Command:
 show clock
Response:
GNS-Router-CPT-EDGE>
10.15.0.50: Raising commandComplete event
10.15.0.50: Host.commands: enable,term len 0,show run
10.15.0.50: Next command from host.commands: enable
10.15.0.50: Notifications: Normal Command to run
10.15.0.50: running: enable

**Comment by cmp-202** [comment] 2017-09-24 12:22
hmm can you show your session text please.

**Comment by cmp-202** [comment] 2017-09-24 12:30
Can you try dropping the \`Send commands\` in the commands array. Thats a whole other process we could do without potentially impacting the process at this point.

**Comment by unchained-za** [comment] 2017-09-24 12:36
Without the 'Send commands': 

10.15.0.50: Connection.connect 
Connected 
10.15.0.50: Connection.ready 
Ready 
10.15.0.50: Connection.shell 
10.15.0.50: Normal prompt detected 
10.15.0.50: Host.commands: show clock,enable,term len 0,show run 
10.15.0.50: Next command from host.commands: show clock 
10.15.0.50: Notifications: Normal Command to run 
10.15.0.50: running: show clock 
10.15.0.50: Normal prompt detected 
10.15.0.50: Command complete: 
Command: 
show clock 
Response: 
GNS-Router-CPT-EDGE> 
10.15.0.50: Raising commandComplete event 
10.15.0.50: Host.commands: enable,term len 0,show run 
10.15.0.50: Next command from host.commands: enable 
10.15.0.50: Notifications: Normal Command to run 
10.15.0.50: running: enable 
10.15.0.50: Check for false prompt or enable 

Then sessionText: 

10.15.0.50: Stream.finish 
10.15.0.50: Session Text: 
Connected to 10.15.0.50 

GNS-Router-CPT-EDGE>show clock 
12:32:27.722 UTC Sun Sep 24 2017 
GNS-Router-CPT-EDGE>enable 
Password: 
% Access denied 

GNS-Router-CPT-EDGE>show run 
^ 
% Invalid input detected at '^' marker. 

GNS-Router-CPT-EDGE> 
10.15.0.50: Stream.close 
10.15.0.50: Connection.close 
Closed

**Comment by cmp-202** [comment] 2017-09-24 13:33
Thanks.
Okay so I can't see anything in the session text to cause a false prompt detection.
What I am seeing is the response looks like it is the previous full buffer which doesn't make sense because the buffer is wiped before the next command is run.

Can you turn off verbose and debug, only have one command 'show clock', remove the three event handlers from host (onEnd, onCommandProcessing and onCommandComplete). 
Can you add the following:
```javascript
host.onData = function(data){console.log(data);}
```
and post the output as a file.
This will show us every raw data event on a new line without processing so we can see exactly what is coming in.

**Comment by unchained-za** [comment] 2017-09-24 13:47
Please see attached, this is an extreme case for a banner for testing that we used previously.
[alloutput.txt](https://github.com/cmp-202/ssh2shell/files/1327353/alloutput.txt)

**Comment by unchained-za** [comment] 2017-09-24 13:57
Here the motd banner doesn't have prompt characters. In both cases the login banner, before the password prompt,  doesn't display. 

In this case the original script works perfectly.

[login.txt](https://github.com/cmp-202/ssh2shell/files/1327358/login.txt)

**Comment by cmp-202** [comment] 2017-09-24 14:37
Thanks. Is that the same response that your post without 'Send commands' would have shown verbose and debug content for? (or at least similar enough)

I will need to come back to this tomorrow its 3:35am here so better hit the sack.

I am going to need to modify my virtual test setup to replicate it. 
Its a tricky one. These edge cases make it complicated to handle prompt detection.

**Comment by unchained-za** [comment] 2017-09-24 14:50
Very similar. I've spent quite a few days on this before asking you, thought I could sort it out by myself, although I'm still very new to node and JS. But this one is tricky and has been a headache before as well in C++ too. 

I appreciate any help with this! 

Regards

**Comment by cmp-202** [comment] 2017-09-24 14:54
Thanks. Yes the only thing I can think of is data events after a false prompt trigger on the banner content is causing the subsequent prompt events to show the buffer from those extra data events and not from the current command response. Every response looks a step behind the command. 

I wonder if I could skip prompt detection on the first run causing a timeout when no more data events are received (first prompt).
I can then handle running the first command with subsequent prompts detected.
Might work or something similar.

**Comment by cmp-202** [comment] 2017-09-24 15:05
Can you edit the lib/ssh2shell.js file on line 61 by adding `this.command && ` just before `this.standardPromt.test(` this will cause it to only check for a prompt if a command has been run.
Then add host.onCommandTimeout handler that does the following `if(this.command === ""){this._nextCommand();};`

**Comment by cmp-202** [comment] 2017-09-24 15:10
```javascript
host.onCommandTimeout = function( command, response, stream, connection ){
    if(this.command === ""){
        this._nextCommand();
    }
}
```

**Comment by unchained-za** [comment] 2017-09-24 16:01
Sorry for my late response, hope you went to sleep! 

That seems to work, I'll test more with the timeout later. 

Thank you so much!

**Comment by cmp-202** [comment] 2017-09-25 10:17
I have opened a new branch called banners. I have modified the code to run the next command when a timeout is triggered by no more data events. This would be the case when the prompt was reached be it with or without a banner. It might be worth also checking for standard prompt at timeout but I haven't bothered with this version as no other prompt type me result at this stage after connection. 

You don't need to do anything in the command timeout handler it is all done for you.
Can you grab the banner branch and try with the new updates and let me know if it works.

**Comment by unchained-za** [comment] 2017-09-25 11:12
This is with no processing an only the 'show clock' command. It seems to just timeout. The same type of response when I do not have the motd banner, then I see the login banner (before the password: prompt) that I don't see here. 

$ node cisco.js 
Connected 
Ready 
Cyril's very > Special >> message to # include ## >#>>## ### 

GNS-Router-CPT-EDGE> 
Timeout error: 10.15.0.50: Command timed out after 10 seconds 
Closed 
$

**Comment by cmp-202** [comment] 2017-09-25 11:52
Okay pull from the branch, turn on debug and try again. (I didn't push my last changes)

**Comment by unchained-za** [comment] 2017-09-25 12:24
See attached pleae. Noprocess.txt is with just the 'show clock' command, while process.txt is with the set of commands including enable. It still seems like the enable password is sent out of sequence.

[noprocess.txt](https://github.com/cmp-202/ssh2shell/files/1329357/noprocess.txt)
[process.txt](https://github.com/cmp-202/ssh2shell/files/1329360/process.txt)

**Comment by cmp-202** [comment] 2017-09-25 13:14
looks like the first prompt timeout is firing twice

**Comment by cmp-202** [comment] 2017-09-25 13:21
So I have cleared the timer when it times out but I don't know if that is the problem but give it a try. I need to hit the sack but tomorrow I will fore up the test hosts and thrash this out properly.

**Comment by unchained-za** [comment] 2017-09-25 13:24
Thank you so much for all your effort! It is really appreciated.

**Comment by cmp-202** [comment] 2017-09-26 09:53
I think I have suscess!
I am getting correct prompt detection with or without a banner containing prompt chars.
This method allows commandProcessing to be trgiggered if there is no cammand loaded.
I added a flag to the host object to enable it or disable adding banner content to the session text `host.showbanner = true`. It was previously dropped.
Update from the banner branch and give it a try.

**Comment by unchained-za** [comment] 2017-09-26 10:15
Thank you so much! 

I'll try it in a while and let you know.

**Comment by unchained-za** [comment] 2017-09-26 10:51
Please see the attached cisco.txt script and the 2 output files with standard and special banners. 

I now get timeouts at the end.

**Comment by cmp-202** [comment] 2017-09-26 11:43
I can't get my test VM test to replicate it so not sure how that is happening. It looks like it is not being reset on the last command.
You will need to add a timeout handler to show what the last sommand and response was (see below).
Can you use the following script with your credentials changed:
```
var host = {
  server:             {     
    host: "10.15.128.3", 
    port: "22", 
    userName: "username", 
    password: "password",
    tryKeyboard:  true
  },
  commands:           [
    "`Send commands`",
    "show clock",
    "enable",
    "term len 0",
    "show run"
  ],
  showBanner: true,
  verbose: true,
  debug: true,
  onCommandProcessing: function( command, response, sshObj, stream ) {
        //Check the command and prompt exits and respond with a 'y' but only does it once
        if (sshObj.debug) {this.emit('msg', this.sshObj.server.host + ": Check for enable");}
        if (sshObj.verbose) {this.emit('msg', this.sshObj.server.host + ": command: " + command + ", response: ||" + response + "||, firstRun: " + sshObj.firstRun);}
        if (command === "enable" && response.indexOf("assword:") > 0 && sshObj.firstRun != true) {
            //This debug message will only run when conditions are met not on every data event so is ok here
            if (sshObj.debug) {this.emit('msg', this.sshObj.server.host + ": Responding to enable with " + sshObj.server.password);}
            sshObj.firstRun = true
            stream.write(sshObj.server.password + '\n');
        }
    },
   onKeyboardInteractive: function(name, instructions, instructionsLang, prompts, finish){
        finish([this.sshObj.server.password]);
    },
    onEnd: function( sessionText, sshObj ) {
        this.emit ("msg", sshObj.server.host + ": Session Text:\n" + sessionText);
    },
    onCommandTimeout: function( command, response, stream, connection ){
       if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout")};
       this.emit ("msg", "command: " + command + "\nResponse:\n" + response);
    }
};

var SSH2Shell = require ('ssh2shell-banners'),
var SSH = new SSH2Shell(host);
SSH.connect();
```

Here is my test.

**Sript:**
```
var host = {
  server: {     
    host:         192.168.0.117,
    port:         22,
    userName:     user,
    password:     password
  },
  showBanner:     true,
  debug:          true,
  verbose:        true,
  commands:       [
    "ls -la",
    "echo 1",
    "echo 2"    
  ],
};

//var SSH2Shell = require ('ssh2shell');
var SSH2Shell = require ('../lib/ssh2shell');

//run the commands in the shell session
var SSH = new SSH2Shell(host),
    callback = function( sessionText ){
          console.log ( "-----Callback session text:\n" + sessionText);
          console.log ( "-----Callback end" );
      }

SSH.connect(callback)
```

**Ouput:**
```
192.168.0.117: Connection.connect
Connected
192.168.0.117: Connection.ready
Ready
192.168.0.117: Connection.shell
192.168.0.117: first prompt detected
192.168.0.117: Host.commands: ls -la,echo 1,echo 2
192.168.0.117: Next command from host.commands: ls -la
192.168.0.117: Notifications: Normal Command to run
192.168.0.117: running: ls -la
192.168.0.117: Normal prompt detected
192.168.0.117: Command complete:
Command:
 ls -la
Response:
total 68
drwxr-xr-x 5 user user  4096 Feb  1  2017 .
drwxr-xr-x 4 root root  4096 Sep  2  2016 ..
-rw------- 1 user user 30384 Sep 26 22:05 .bash_history
-rw-r--r-- 1 user user   220 Aug 18  2016 .bash_logout
-rw-r--r-- 1 user user  3771 Aug 18  2016 .bashrc
drwx------ 2 user user  4096 Aug 18  2016 .cache
drwxrwxr-x 2 user user  4096 Sep  1  2016 .nano
-rw-r--r-- 1 user user   655 Aug 18  2016 .profile
drwx------ 2 user user  4096 Sep 30  2016 .ssh
-rw-r--r-- 1 user user     0 Aug 18  2016 .sudo_as_admin_successful
user@ubuntu:~$
192.168.0.117: Raising commandComplete event
192.168.0.117: Class.commandComplete
192.168.0.117: Host.commands: echo 1,echo 2
192.168.0.117: Next command from host.commands: echo 1
192.168.0.117: Notifications: Normal Command to run
192.168.0.117: running: echo 1
192.168.0.117: Normal prompt detected
192.168.0.117: Command complete:
Command:
 echo 1
Response:
1
user@ubuntu:~$
192.168.0.117: Raising commandComplete event
192.168.0.117: Class.commandComplete
192.168.0.117: Host.commands: echo 2
192.168.0.117: Next command from host.commands: echo 2
192.168.0.117: Notifications: Normal Command to run
192.168.0.117: running: echo 2
192.168.0.117: Normal prompt detected
192.168.0.117: Command complete:
Command:
 echo 2
Response:
2
user@ubuntu:~$
192.168.0.117: Raising commandComplete event
192.168.0.117: Class.commandComplete
192.168.0.117: No commands so exit
192.168.0.117: Run exit
192.168.0.117: Exit command: Stream: close
192.168.0.117: Stream.finish
192.168.0.117: Class.end
-----Callback session text:
Connected to 192.168.0.117
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-96-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

117 packages can be updated.
0 updates are security updates.


banner content
Last login: Wed Sep 27 00:09:04 2017 from 192.168.0.0
user@ubuntu:~$ ls -la
total 68
drwxr-xr-x 5 user user  4096 Feb  1  2017 .
drwxr-xr-x 4 root root  4096 Sep  2  2016 ..
-rw------- 1 user user 30384 Sep 26 22:05 .bash_history
-rw-r--r-- 1 user user   220 Aug 18  2016 .bash_logout
-rw-r--r-- 1 user user  3771 Aug 18  2016 .bashrc
drwx------ 2 user user  4096 Aug 18  2016 .cache
drwxrwxr-x 2 user user  4096 Sep  1  2016 .nano
-rw-r--r-- 1 user user   655 Aug 18  2016 .profile
drwx------ 2 user user  4096 Sep 30  2016 .ssh
-rw-r--r-- 1 user user     0 Aug 18  2016 .sudo_as_admin_successful
user@ubuntu:~$ echo 1
1
user@ubuntu:~$ echo 2
2
user@ubuntu:~$
-----Callback end
192.168.0.117: Stream.close
192.168.0.117: Connection.close
Closed
```
No Timeout.

**Comment by unchained-za** [comment] 2017-09-26 12:00
It just hangs after the show clock command. Rather confusing at this stage. 

The best response thus far was when I made the small change to ssh2shell and with the addition of the onTimeout handler 

10.15.0.50: Connection.connect 
Connected 
10.15.0.50: Connection.ready 
Ready 
10.15.0.50: Connection.shell 
10.15.0.50: Check for enable 
10.15.0.50: command: , response: ||Cyril's very > Special >> message to # include ## >#>>## ###||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: , response: ||Cyril's very > Special >> message to # include ## >#>>## ### 
GNS-Router-CPT-EDGE>||, firstRun: undefined 
10.15.0.50: first prompt detected 
10.15.0.50: Host.commands: `Send commands`,show clock,enable,term len 0,show run 
10.15.0.50: Next command from host.commands: `Send commands` 
10.15.0.50: Notifications: sessionText output 
Send commands 
10.15.0.50: Host.commands: show clock,enable,term len 0,show run 
10.15.0.50: Next command from host.commands: show clock 
10.15.0.50: Notifications: Normal Command to run 
10.15.0.50: running: show clock 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||s||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||sh||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||sho||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show ||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show c||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show cl||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clo||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show cloc||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clock||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clock 
||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clock 
11:56:18.255 UTC Tue Sep 26 2017 
GNS-Router-CPT-EDGE>||, firstRun: undefined 
10.15.0.50: host.onCommandTimeout 
command: show clock 
Response: 
show clock 
11:56:18.255 UTC Tue Sep 26 2017 
GNS-Router-CPT-EDGE>

**Comment by cmp-202** [comment] 2017-09-26 12:29
Check the issue posts I adjusted that scrip to remove all the onCommandProcessing debug and verbose not long after posting it. Also you can limit the commands to just show clock. Review the script to make sure it is ok from your perspective and double check you are using the most recent branch just in case. Output shouldn't be so cluttered after that.On 27/09/2017 1:00 AM, unchained-za <notifications@github.com> wrote:It just hangs after the show clock command. Rather confusing at this stage. 

The best response thus far was when I made the small change to ssh2shell and with the addition of the onTimeout handler 

10.15.0.50: Connection.connect 
Connected 
10.15.0.50: Connection.ready 
Ready 
10.15.0.50: Connection.shell 
10.15.0.50: Check for enable 
10.15.0.50: command: , response: ||Cyril's very > Special >> message to # include ## >#>>## ###||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: , response: ||Cyril's very > Special >> message to # include ## >#>>## ### 
GNS-Router-CPT-EDGE>||, firstRun: undefined 
10.15.0.50: first prompt detected 
10.15.0.50: Host.commands: `Send commands`,show clock,enable,term len 0,show run 
10.15.0.50: Next command from host.commands: `Send commands` 
10.15.0.50: Notifications: sessionText output 
Send commands 
10.15.0.50: Host.commands: show clock,enable,term len 0,show run 
10.15.0.50: Next command from host.commands: show clock 
10.15.0.50: Notifications: Normal Command to run 
10.15.0.50: running: show clock 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||s||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||sh||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||sho||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show ||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show c||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show cl||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clo||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show cloc||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clock||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clock 
||, firstRun: undefined 
10.15.0.50: Check for enable 
10.15.0.50: command: show clock, response: ||show clock 
11:56:18.255 UTC Tue Sep 26 2017 
GNS-Router-CPT-EDGE>||, firstRun: undefined 
10.15.0.50: host.onCommandTimeout 
command: show clock 
Response: 
show clock 
11:56:18.255 UTC Tue Sep 26 2017 
GNS-Router-CPT-EDGE>

**Comment by cmp-202** [comment] 2017-09-26 12:41
Its not detecting the prompt after the command based on that output. Grr that makes no sense what is different from it working on mine but failing on yours. If the command is present test was failing then no prompt detection would result and then timeout but that would cause my test to fail.

**Comment by unchained-za** [comment] 2017-09-26 12:47
I'm in a bit of a crisis at work now, will try and trace through the steps again this evening. Here it is 2:46 pm

**Comment by unchained-za** [comment] 2017-09-26 14:47
I've retried everything with a minimal script and only the show clock command and it still hangs at the end.

10.15.0.50: Connection.connect
Connected
10.15.0.50: Connection.ready
Ready
10.15.0.50: Connection.shell
10.15.0.50: first prompt detected
10.15.0.50: Host.commands: show clock
10.15.0.50: Next command from host.commands: show clock
10.15.0.50: Notifications: Normal Command to run
10.15.0.50: running: show clock
10.15.0.50: host.onCommandTimeout
command: show clock
Response:
show clock
14:15:12.496 UTC Tue Sep 26 2017
GNS-Router-CPT-EDGE>
^C

The script (need the algorithms to connect to cisco):

var host = {
    server:             {     
        host: "10.15.0.50", 
        port: "22", 
        userName: "username", 
        password: "password",
        tryKeyboard:  true,
        algorithms: {
            kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
            cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc' ]
        }
    },
    commands:           [
        "show clock"
    ],
    showBanner: true,
    verbose: true,
    debug: true,
    onKeyboardInteractive: function(name, instructions, instructionsLang, prompts, finish){
        finish([this.sshObj.server.password]);
    },
    onEnd: function( sessionText, sshObj ) {
        this.emit ("msg", sshObj.server.host + ": Session Text:\n" + sessionText);
    },
    onCommandTimeout: function( command, response, stream, connection ){
        if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout")};
        this.emit ("msg", "command: " + command + "\nResponse:\n" + response);
    }
};

var SSH2Shell = require ('ssh2shell-banners')
var SSH = new SSH2Shell(host);
SSH.connect();

**Comment by cmp-202** [comment] 2017-09-27 00:40
Sorry about all this mucking around. I have modified the test statements which will seperate the prompt detection from there being no command which will hopefuly deal with the prompt not being detected from the first command.

I have updated the branch could you try it again. If it fails it might help adding the onData event back in to see what is in the buffer. Numbering the data events could help.

Regarding algorithms: All the algorithms you list in your config are default unless I have compared the defaults wrong which means you should not need to set them for keyboard interactive to work. The orriginal work on keyboard interactive was done for cisco connections. Will it not connect if it is not manualy set?

**Comment by unchained-za** [comment] 2017-09-27 06:51
Without the algorithms I get: 

10.15.0.50: Connection.connect 
Connected 
10.15.0.50: Connection.error 
10.15.0.50: Class.error 
Error: Handshake failed: no matching client->server cipher, Level: protocol 
10.15.0.50: Connection.close 
Closed 

With only the show clock command, this is the output before it hangs with the added onData: 

10.15.0.50: Connection.connect 
Connected 
10.15.0.50: Connection.ready 
Ready 
10.15.0.50: Connection.shell 
10.15.0.50: host.onData: Cyril's very > Special >> message to # include ## >#>>## ### 
10.15.0.50: host.onData: 
GNS-Router-CPT-EDGE> 
10.15.0.50: first prompt detected 
10.15.0.50: Host.commands: show clock 
10.15.0.50: Next command from host.commands: show clock 
10.15.0.50: Notifications: Normal Command to run 
10.15.0.50: running: show clock 
10.15.0.50: host.onData: s 
10.15.0.50: host.onData: h 
10.15.0.50: host.onData: o 
10.15.0.50: host.onData: w 
10.15.0.50: host.onData: 
10.15.0.50: host.onData: c 
10.15.0.50: host.onData: l 
10.15.0.50: host.onData: o 
10.15.0.50: host.onData: c 
10.15.0.50: host.onData: k 
10.15.0.50: host.onData: 

10.15.0.50: host.onData: 06:49:30.931 UTC Wed Sep 27 2017 
GNS-Router-CPT-EDGE> 
10.15.0.50: host.onCommandTimeout 
command: show clock 
Response: 
show clock 
06:49:30.931 UTC Wed Sep 27 2017 
GNS-Router-CPT-EDGE>

**Comment by cmp-202** [comment] 2017-09-27 08:42
Your right my bad! I looked through the code and saw that no default algorithms were set. Must need sleep sorry.

I have modified the code to detect that no new data events have been raised every time (potential prompt) causing a timeout at which point I handle the three possible actions. 1) command so test prompt 2) command no prompt so in command proccessing flow 3) no command so presume first prompt.

I also added a console.log("banner branch 1") so we know you have what I have. It worked on my test set up but doesn't mean much. 
Get the branch, give it a try and post your output. (fingers, eyes, legs, hell everything crossed)

**Comment by unchained-za** [comment] 2017-09-27 09:31
Congratulations! Seems like it is working.

I tried with the minimal script and the one with the enable to get the running config. Both scripts and results (shortened config) attached.

Now to sort out the rest of the probs. I have to test for a working set of credentials out of a number of sets, check whether enable is required (> or # prompt) and then figure out how to connect to the Cisco wireless LAN controller that prompts for username and password, probably keyboard-interactive.

[output2.txt](https://github.com/cmp-202/ssh2shell/files/1336506/output2.txt)
[output1.txt](https://github.com/cmp-202/ssh2shell/files/1336505/output1.txt)
[script1.txt](https://github.com/cmp-202/ssh2shell/files/1336503/script1.txt)
[script2.txt](https://github.com/cmp-202/ssh2shell/files/1336504/script2.txt)

**Comment by unchained-za** [comment] 2017-09-27 09:32
BTW, it shows banner branch, not banner branch 1

**Comment by cmp-202** [comment] 2017-09-27 09:57
Yes coded one thing posted another.
In script two can you remove the first condition block in the onCommandProcessing handler. Its the code added to initially get it working. 
Remove the following:
```javascript
if (command === ""
                && response.match("[" + sshObj.standardPrompt + "]$")
                && response.match("[" + sshObj.standardPrompt + "]$").length > 0 
                && sshObj.falsePromptDetected === false){
            sshObj.falsePromptDetected = true;
            sshObj.sessionText += response;
            response = "";
        }        
        else 
```
re probs:
Credentials:
Not sure how you are doing your credential check but if it is: command then required input then responce indicating pass or fail. I would recommend for onCommandProcessing for the input required detection and onCommandComplete to check result.
If it is: command then responce indicating pass or fail. Then use onCommandComplete.
Enable:
Again one of the two options above
Connect to wireless controller:
Are you doing that through a connection to another router or connecting directly to different individual hosts in one process?
Using the host.hosts array you can connect to multiple hosts using individual host objects for each connection be it one after the other or hopping from one host to another. There is a lot in the readme about tunneling method and there is an example in the ssh2shell/tests folder.

**Comment by unchained-za** [comment] 2017-09-27 10:09
Thanks so much for all your help and tips / guidance, I really appreciate it. This package makes the use of SSH so much simpler. I'll try to stop bugging you for the moment.

**Comment by cmp-202** [comment] 2017-09-27 10:15
My pleasure, its been a bit of a battle thanks for your patience. 
I think it has helped make the prompt detection better overall. I like the idea of waiting until all the data events are received before checking.

Given we seemed to have nailed it would you like to close the issue.
I am just working on publishing the new changes to npm and I have deleted the banner branch.
Cheers,

Andrew

**Comment by unchained-za** [comment] 2017-09-27 10:24
Seems fine to close now, thank you again!

**Comment by cmp-202** [comment] 2017-09-27 10:28
npm package updated

**Closed by cmp-202** 2017-09-27 10:28 UTC
